sudo: required
services:
  - docker

before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hellp npm run lint
deploy:
  provider: heroku
  api_key:
    secure:
      asd
  on: heroku_production
  app: probot-secumfex
